#!/usr/bin/env python3

"""
Converts Twist velocity commands into TwistStamped messages.

This node adapts the velocity commands generated by the safety layer to the
message format required by the ros2_control Diff Drive Controller.
"""

from geometry_msgs.msg import Twist, TwistStamped
from sensor_msgs.msg import LaserScan   
import rclpy
from rclpy.node import Node

class TwistToStamped(Node):
    """
    ROS 2 node that converts Twist messages to TwistStamped messages.
    """

    def __init__(self):
        """
        Initialize publishers and subscribers for velocity command conversion.
        """
        super().__init__('twist_to_stamped')

        self.sub = self.create_subscription(
            Twist,
            '/cmd_vel',
            self.cb,
            10
        )

        self.pub = self.create_publisher(
            TwistStamped,
            '/mensabot_base_controller/cmd_vel',
            10
        )

        self.get_logger().info("cmd_vel transform node has been started.")

    def cb(self, msg):
        """
        Convert an incoming Twist message into a TwistStamped message.

        Args:
            msg: Incoming velocity command.
        """
        out = TwistStamped()
        out.header.stamp = self.get_clock().now().to_msg()
        out.header.frame_id = "base_link"
        out.twist = msg
        self.pub.publish(out) 

def main(args=None):
    """
    Entry point for the TwistToStamped node.

    Initializes rclpy, spins the node, and performs
    a clean shutdown when the node stops.
    """
    rclpy.init(args=args)
    node = TwistToStamped()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()